print("Ejemplo de listas")
arcoiris=["verde","azul","morado"]
print(arcoiris)
longitud=len(arcoiris)
print("Elementos que contiene la lista arcoiris ", longitud)
print(f"Elementos que contiene la lista arcoiris v2 {longitud}")
print("Accediendo a un elemento de la lista")
print(arcoiris[1])
print(f"Elemento en la posision 0 es {arcoiris[0]}")
print(f"Elemento en la posision 0 es: ",arcoiris[0])
print("Agregar a un elemento de la lista")
print(arcoiris)
arcoiris.append("naranja")
print(arcoiris)
print("Listar lo elementos de la lista ciclo for")
for Ramirez in arcoiris:
    print(Ramirez)